In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))  

2.5
2.5
1.118033988749895


In [8]:
x=np.random.randint(1,10)
print(x)
y=np.random.randint(0,100,size=5)
print(y)
z=np.random.randint(10,21,size=(3,3))
print(z)    

5
[57 87 89 60 26]
[[20 14 15]
 [16 12 13]
 [18 18 19]]


In [9]:

a=np.random.rand()
print(a)
b=np.random.rand(5)
print(b)
c=np.random.rand(2,3)
print(c)

0.3115507760516044
[0.6303879  0.48483243 0.4414857  0.07523241 0.82155533]
[[0.53846674 0.3429155  0.90672509]
 [0.92501876 0.43937636 0.5726314 ]]


In [73]:
x=np.random.randint(10,size=6)
print(x)

[2 5 3 6 0 4]


In [74]:
import pandas as pd

In [76]:
s=pd.Series([10,20,49,6,8])
print(s)

0    10
1    20
2    49
3     6
4     8
dtype: int64


In [78]:
n=input("enter name")
a=int(input("enter age"))

data={"name":[n],"age":[a]}
df=pd.DataFrame(data)
print(df)

      name  age
0  raashid   12


In [89]:
data ={
    "name":["alice","bob","charlie"],
    "age":[25,30,None]
}
df=pd.DataFrame(data)
print(df.head())
print(df.tail(2))
df.info()
df.describe() 
df.shape
df.iloc[1]
df.loc[0] 
df.isnull()
df.dropna()
df.fillna(0)

      name   age
0    alice  25.0
1      bob  30.0
2  charlie   NaN
      name   age
1      bob  30.0
2  charlie   NaN
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    3 non-null      object 
 1   age     2 non-null      float64
dtypes: float64(1), object(1)
memory usage: 180.0+ bytes


name   age
0    alice  25.0
1      bob  30.0
2  charlie   0.0

In [90]:
df['age'].fillna(df['age'].mean(), inplace=True)
print(df)   

      name   age
0    alice  25.0
1      bob  30.0
2  charlie  27.5


C:\Users\user\AppData\Local\Temp\ipykernel_15012\4203512716.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(), inplace=True)
