In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))  

2.5
2.5
1.118033988749895


In [8]:
x=np.random.randint(1,10)
print(x)
y=np.random.randint(0,100,size=5)
print(y)
z=np.random.randint(10,21,size=(3,3))
print(z)    

5
[57 87 89 60 26]
[[20 14 15]
 [16 12 13]
 [18 18 19]]


In [9]:

a=np.random.rand()
print(a)
b=np.random.rand(5)
print(b)
c=np.random.rand(2,3)
print(c)

0.3115507760516044
[0.6303879  0.48483243 0.4414857  0.07523241 0.82155533]
[[0.53846674 0.3429155  0.90672509]
 [0.92501876 0.43937636 0.5726314 ]]


In [73]:
x=np.random.randint(10,size=6)
print(x)

[2 5 3 6 0 4]


In [74]:
import pandas as pd

In [76]:
s=pd.Series([10,20,49,6,8])
print(s)

0    10
1    20
2    49
3     6
4     8
dtype: int64


In [78]:
n=input("enter name")
a=int(input("enter age"))

data={"name":[n],"age":[a]}
df=pd.DataFrame(data)
print(df)

      name  age
0  raashid   12


In [80]:
data ={
    "name":["alice","bob","charlie"],
    "age":[25,30,35]
}
df=pd.DataFrame(data)
print(df.head())
print(df.tail(2))
df.info()

      name  age
0    alice   25
1      bob   30
2  charlie   35
      name  age
1      bob   30
2  charlie   35
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    3 non-null      object
 1   age     3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes
